# Inserts a blank line between shell prompts
add_newline = true


format = """\
[  â•­â”€ ](208)$shell[oberonï…º ](8)$directory$python$git_branch $custom$battery
[  â•°â•®](208)$git_status $all\
[   â•°â”€â”€â”€ï¤‰](208)$character($style)"""


#ğŸŒ©ï¸ğŸŒ±â‡ â¯ â‡ âš¡ ïª² ï…º ğŸ” ï€£ ï€£ ï¦— ğŸ›¡ î‚  ï‘ _ ï„¡ ğŸ”Œ
# ï‰„   ï‰„   ï‰ƒ   ï‰ƒ   ï‰‚   ï‰‚   ï‰   ï‰   ï‰€  ï‰€

[character]
success_symbol = "[ï‡‰   ](73)"
error_symbol = "[âœ—](90)"


[git_branch]
symbol = "ï¬« "
format = " [ï¥Œ$remote_name](202)[ $symbol$branch](3) "
style = '3'
truncation_length = 15
truncation_symbol = "â€¦/"
only_attached = false
always_show_remote = true

[cmd_duration]
format="[\\(took $duration\\)]($style)"
style='11'
min_time = 1

[git_status]
# conflicted = "âš”ï¸{$count}"
# ahead = "ğŸï¸ğŸ’¨Ã—${count}"
# behind = "ğŸ¢Ã—${count}"
# diverged = "ğŸ”±ğŸï¸ğŸ’¨Ã—${ahead_count} ğŸ¢Ã—${behind_count}"
# untracked = "ğŸ›¤ï¸Ã—${count}"
# stashed = "ğŸ“¦"
# modified = "ğŸ“Ã—${count}"
# staged = "ğŸ—ƒï¸Ã—${count}"
# renamed = "ğŸ“›Ã—${count}"
# deleted = "ğŸ—‘ï¸Ã—${count}"
style = "9"
format = "[ [github ï¦µ](9)adrianmnh\\[$all_status$ahead_behind\\]]($style)"
disabled=false

[username]
style_user = "8"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = true

[directory]
style = '11'
truncation_length = 1
truncation_symbol = "../~"
# fish_style_pwd_dir_length=2
home_symbol = "ïŸ "
read_only_style = "160"
read_only = " ï¦‚"
format = "[$read_only]($read_only_style)[$path]($style)"

[directory.substitutions]
"F:"=" ï±² "

[shell]
style='8'
fish_indicator = "ïœ¹"
powershell_indicator = "âš¡"
unknown_indicator = "shell"
format='[$indicator]($style)'
disabled = false

[python]
symbol = "ï Ÿ "
python_binary = "python3"
style='2'
format='[ (\($virtualenv\))]($style) via [$symbol$version]($style)'

[custom.tztime]
# command = 'date +"%Z %A%a %b%B %d %m%Y %l:%M%p"'
command = 'date +"%m-%d-%y %l:%M%P"'
when = "true"
style="8"
format = '[ $symbol( \[$output)\] ]($style)'
symbol = "ï€—"

# [custom.F]
# command = "echo foo" # shows output of command
# # #files = ["foo"] # can specify filters but wildcards are not supported
# # when = "$HOME == $PWD"
# # when = """'F:' == '$PWD' """
# when="true"
# style='8'
# symbol="ğŸŒ´$outputğŸŒ´"
# format = "[$symbol]($style)transcending"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’¦ "
format="[$symbol$percentage]($style) "
disabled=false

[[battery.display]] # RED 0-9%
threshold = 10
style = "160"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€ "

[[battery.display]] # RED 10-15%
threshold = 15
style = "160"
discharging_symbol = "ğŸ’€ "

[[battery.display]] # RED 15-30%
threshold = 30
style = "160"
discharging_symbol = "ï‰ƒ  "

[[battery.display]] # ORANGE 30-55%
threshold = 55
style = "208"
discharging_symbol='ï‰‚  '

[[battery.display]] # gray 55-75%
threshold = 75
style = "109"
discharging_symbol='ï‰  '

[[battery.display]] # bright green 75-98%
threshold = 100
style = "76"
discharging_symbol='ğŸ’¦'

[[battery.display]] # bright green 99-100%
threshold = 101
style = "76"
discharging_symbol='ğŸ’¦'
charging_symbol = 'âš¡ï¸'